### ISSUE TITLE
Indigo Dashboard: Scroller masks out subview

### ISSUE THREAD

**Issue by ghulands** [indigo-astronomy/CloudMakers-INDIGO-applications#11]
When expanding all the properties for a device, the scroller on the right crops out the controls below. No horizontal scroller is present. Maybe make the subview a little smaller so when the scroller appears it won't crop it out, or dynamically resize the subviews.

![image](https://user-images.githubusercontent.com/127462/72125186-7e57b700-331c-11ea-98d5-452c52bdfded.png)

**Comment by sanderberents** [comment]
This was fixed in build 4.7_745. The scrollbar is now always hidden for this panel so nothing is cropped, but it can still be scrolled.
