### ISSUE TITLE
Solving with astrometry

### ISSUE THREAD

**Issue by mworion** [indigo-astronomy/CloudMakers-INDIGO-applications#17]
Hi,

interestingly I tested solving an image with 4 different solvers:
1: ASTAP
2: KStars - Astrometry.net
3: Cloudmakers - Astrometry.net
4. nova.astrometry.net Online - Astrometry.net

where 1, 2, 4 show similar results (with small errors) and 3 is different with high errors. I attach the WCS files from 2 + 3 and the fits image for you. Some parts are identical, some very different. Any ideas welcome.

[Archiv.zip](https://github.com/indigo-astronomy/CloudMakers-INDIGO-applications/files/4547818/Archiv.zip)
[2020-04-27-test.fits.zip](https://github.com/indigo-astronomy/CloudMakers-INDIGO-applications/files/4547820/2020-04-27-test.fits.zip)

Michel

**Comment by polakovic** [comment]
Hi Michael,

did you use the same index files as that one chosen by online astrometry.net?
Local version also doesn't have some of the pre-processing tools used by
the online version due to native portability issues. Local version has a
special purpose - to act as a local server for our AstroImager/AstroDSLR
and for this purpose it is sufficient. But it is not necessary true in
general.

Regards, Peter

**Comment by mworion** [comment]
Hi Peter,

these are the identical index files (I used astrometry to download them) and used them from KStars (to be precise the binaries for image2xy and solve-field) like you do.

So solving is done by my software setting same astrometry.cfg and just calling these two binaries (either from KStars or astrometry. There is no preprocessing at all and the only difference are the binaries.

Attached some images.
Michel
![Bildschirmfoto 2020-04-28 um 22 20 49](https://user-images.githubusercontent.com/6632980/80534197-23b39b00-899f-11ea-96c6-25b0adeae23b.png)
![Bildschirmfoto 2020-04-28 um 22 20 22](https://user-images.githubusercontent.com/6632980/80534202-257d5e80-899f-11ea-9d37-454aa1b56554.png)
![Bildschirmfoto 2020-04-28 um 22 11 38](https://user-images.githubusercontent.com/6632980/80534207-27472200-899f-11ea-8a88-9e074c64fc70.png)

**Comment by polakovic** [comment]
Hi Michel, there is always some preprocessing involved with online (and
also any other complete) astrometry.net. It may affect which stars are
selected and after all what is the result. Local astrometry is simplified,
only the core engine is ported to native macOS. I think this is the reason
why it sometimes produces different results. Peter

**Comment by mworion** [comment]
Hi Peter,

fully agree. But the way your implementation is used compared the KStars's one is identically (Calling the two binaries with same parameter set). Only difference is the version number of the Astrometry.net sources (yours 0.67, KStars 0.83) and in your setup the option -nofits2fits (as this is depreciated in the 0.83 version and causes errors). 

Do you have other clues ?

Michel

**Comment by polakovic** [comment]
Hi Michel, sorry I have no other idea. Peter
