### ISSUE TITLE
AT - On mount connection, AT site location is sometimes overwritten by values in config file

### ISSUE THREAD

**Issue by JohanBakk** [indigo-astronomy/CloudMakers-INDIGO-applications#2]
In AstroTelescope, at the moment of mount connection, the site location in the AT preferences is sometimes overwritten by values present in the mount config file. Easy work around is to set the proper values in the mount config file.

**Comment by polakovic** [comment]
Fixed in 3.9_425.

This ugly bug actually affects also AI, AG and AD and explains many other asynchronous issues as well!

**Comment by polakovic** [comment]
Sorry, Fixed in 3.9_426.
