### ISSUE TITLE
Connection refused messages

### ISSUE THREAD

**Issue by JohanBakk** [indigo-astronomy/CloudMakers-INDIGO-applications#3]
Sometimes the AT, AI or AG application complain about connections that are refused, until they are restarted. Such as:

19:14:26.960 INDIGO Service AstroGuider was removed
19:14:26.961 AstroGuider is lost
19:14:26.962 XML Parser: parser finished
19:14:26.962 Server MacBook-Astro.local.:52121 disconnected
19:14:27.669 INDIGO Service AstroGuider was discovered
19:14:27.719 INDIGO Service AstroGuider was successfully resolved to MacBook-Astro.local.:53321
19:14:27.739 Server MacBook-Astro.local.:53321 thread started
19:14:27.740 Server MacBook-Astro.local.:53321 (AstroGuider, http://MacBook-Astro.local.:53321) connected
19:14:27.741 AstroGuider is found
19:14:32.008 Can't connect to socket (Connection refused)
19:14:36.968 Can't connect to socket (Connection refused)
19:14:43.084 Can't connect to socket (Connection refused)
19:14:46.982 Can't connect to socket (Connection refused)
19:14:51.978 Can't connect to socket (Connection refused)
19:14:56.986 Can't connect to socket (Connection refused)
19:15:01.991 Can't connect to socket (Connection refused)
19:15:06.995 Can't connect to socket (Connection refused)
19:15:11.995 Can't connect to socket (Connection refused)

Easy way to reproduce is to have multiple applications running and in one the application change a preference and click Done. The application will remove and republish itself, after which (sometimes) the other application start reporting the error.

**Comment by polakovic** [comment]
Fixed in 3.9_425
