### ISSUE TITLE
AT - Clear log / Save log menu items are sometimes in the wrong place or  

### ISSUE THREAD

**Issue by JohanBakk** [indigo-astronomy/CloudMakers-INDIGO-applications#4]
After a fresh startup of AT, the menu items Clear log / Save log are in the proper place in the Control menu. The Control menu also contains history on selected targets. After a number of mutations of target in the history, the Clear log / Save log menu items sometimes get lost. When AT is restarted, they are back.

**Comment by polakovic** [comment]
Fixed in 3.9_425
