### ISSUE TITLE
AT - Double connections to mount after mount driver restarts

### ISSUE THREAD

**Issue by JohanBakk** [indigo-astronomy/CloudMakers-INDIGO-applications#5]
Sometime when a mount driver is restarted (e.g. from ICP with Restart Server), AT will open up a second connection to the mount driver and send all commands twice.

**Comment by polakovic** [comment]
Maybe fixed by 3.9_425, not fully tested yet

**Comment by polakovic** [comment]
Fixed by 3.9_425
