### ISSUE TITLE
AT - Enhancement request; slew speed buttons in the menu bar of AT

### ISSUE THREAD

**Issue by JohanBakk** [indigo-astronomy/CloudMakers-INDIGO-applications#6]
Would be nice to have the "slew speed' buttons1-4  in the menu bar of AT.

**Comment by polakovic** [comment]
In 3.9_426 toolbar can be customised to contain buttons from manual control panel.

![screenshot 2019-01-04 at 14 56 48](https://user-images.githubusercontent.com/5428151/50691522-447d1200-1031-11e9-9726-f6bdddbf5d8e.jpg)

**Comment by JohanBakk** [comment]
Great! You are closing issues in high speed! :-D 

When will you publish 426?
