### ISSUE TITLE
AT - Enhancement request; option to re-use or delete existing alignment points

### ISSUE THREAD

**Issue by JohanBakk** [indigo-astronomy/CloudMakers-INDIGO-applications#8]
Would be nice to make the user aware ( at the time of AT connecting to the mount) that the server has active alignment points. Now that SynScan driver persists the alignment points by default, there is the risk that on a next session, the old alignment points are overlooked. A possible solution is to have AT ask the user on connection to the mount whether to re-use or delete the existing alignment points. Other option is to make active alignment points manageable from AT (in a panel?).

**Comment by polakovic** [comment]
Fixed in 3.9_425
